name: Despliegue Frontend Angular

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 1. Descargar el código nuevo
      uses: actions/checkout@v4

    - name: 2. Instalar dependencias
      run: npm install

    - name: 3. Compilar Angular para producción
      run: npx ng build --configuration production --base-href /SistemaReembolsos/

    - name: 4. Copiar archivos al servidor IIS (wwwroot)
      run: |
        Copy-Item -Path "dist\reembolsos-webapp\browser\*" -Destination "C:\inetpub\wwwroot\SistemaReembolsos" -Recurse -Force
